[project]
name = "mini-project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "keras>=3.9.0",
    "pandas>=2.2.3",
    "tensorflow>=2.18.0",
]
