[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "seaborn>=0.13.2",
    "shap>=0.46.0",
    "xverse==1.0.5",
]
